### PR TITLE
Generate action type support / Remove hardcoded action type support

### PR DESCRIPTION
**Pull request by sloretz**
This removes the hardcoded type support for actions so that it doesn't conflict with the generated typesupport

### CODE REVIEW

**Comment by sloretz** [comment]
CI with connected PRs to fully generate action type support

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5513/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2177/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4549/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5413/)

**Comment by sloretz** [comment]
Checking test failures on linux [Build Status](https://ci.ros2.org/job/ci_linux/5517/)

**Comment by sloretz** [comment]
Checking linker failures on OSX [Build Status](https://ci.ros2.org/job/ci_osx/4554/)

**Comment by sloretz** [comment]
CI with ros2/rosidl_typesupport#38 and ros2/rosidl#318

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5519/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2181/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4556/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5417/)

**Comment by sloretz** [comment]
CI with ros2/rosidl_typesupport#36 and ros2/rosidl#312

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5521/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2183/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4558/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5419/)

**Comment by sloretz** [comment]
CI with ros2/rosidl_typesupport#36 and ros2/rosidl#312 after addressing all comments

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5530/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2189/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4564/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5425/)

**Review by hidmic — APPROVED** [review]
LGTM!

**Pull request merged**
