### PR TITLE
Added BoundedPlainSequences to test_msgs

### PR DESCRIPTION
**Pull request by MiguelCompany**
Adding one message definition with bounded sequences of POD types

Depends on ros2/test_interface_files#14

### CODE REVIEW

**Review by hidmic — COMMENTED** [review]
Only comment here follows https://github.com/ros2/test_interface_files/pull/14#discussion_r652111888. Drop the message types you don't need.

**Review by hidmic — APPROVED** [review]
@MiguelCompany don't forget to update the PR title!

**Comment by MiguelCompany** [comment]
> @MiguelCompany don't forget to update the PR title!

@hidmic Done. I've also updated the description.

**Comment by hidmic** [comment]
CI up to `rmw_fastrtps_cpp`, `rmw_fastrtps_dynamic_cpp`, `rcl_interfaces` and `test_rmw_implementation`:

* Linux [Build Status](https://ci.ros2.org/job/ci_linux/14795/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9544/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12461/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14942/)

**Comment by hidmic** [comment]
MacOS CI, one more time:
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12630/)

**Comment by hidmic** [comment]
CI again as it's been a while:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14975/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9716/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12655/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15139/)

**Pull request merged**
