### PR TITLE
Parameters roundup

### PR DESCRIPTION
**Pull request by esteve**
This should fix any inconsistencies and reflect the feedback from ros2/ros2#46

@dirk-thomas @jacquelinekay @tfoote @wjwwood please review

Connects to ros2/ros2#46

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
A couple minor changes to the comment in the message files:
- The comment in the renamed `ParameterEventDescriptors` file needs to be updated to `descriptors`
- The comment for the reply in `SetParameters.srv` seems to not make sense anymore

The following comments are from the referenced ticket:
- `DescribeParameters` should explicitly mention same length (beside same order)
- `ParameterEvent`: mention constraints about entries with same names in different fields as discussed (same for `ParameterDescriptor`)

**Comment by esteve** [comment]
@dirk-thomas done.

**Comment by esteve** [comment]
@dirk-thomas fixed.

**Comment by dirk-thomas** [comment]
Beside the last micro comment: +1

**Pull request merged**
