### PR TITLE
Dabonnie/add test header message

### PR DESCRIPTION
**Pull request by dabonnie**
Add test message needed by https://github.com/ros2/rclcpp/pull/1080

### CODE REVIEW

**Comment by dabonnie** [comment]
FYI @wjwwood @jacobperron

**Comment by jacobperron** [comment]
We can't accept this PR as it introduces a circular dependency at the repository level:  `test_msgs` (rcl_interfaces) -> `std_msgs` (common_interfaces) -> `builtin_interfaces` (rcl_interfaces).

**Comment by dabonnie** [comment]
Closing this as we'll open another with your proposal (copy the message structure rather than use a dependency).

**Comment by jacobperron** [comment]
> Closing this as we'll open another with your proposal (copy the message structure rather than use a dependency).

Please consider generating the message directly in `rclcpp`. I think it will be much neater (and easily refactored) versus adding a new public message to `test_msgs`.

**Pull request closed without merging**
