### PR TITLE
lifecycle_msgs: remove non-ASCII chars from field comments

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

I'm working on an old platform with an ancient version of GCC which isn't capable of processing files with non-ASCII chars in them.

The unicode apostrophes caused build failures, so 48d66fbb removes them.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
This was never really a problem until we upgraded `rosidl_generator_c` et al. to post https://github.com/ros2/rosidl/pull/593.

**Comment by clalancette** [comment]
I'm torn on this one.

On the one hand, there is no reason that this needs to be Unicode; regular ASCII apostrophe will be just fine, and will fix your use case.

On the other hand, we most definitely should support Unicode inside of comments in `.msg` files.  This was a test of that, though more of an implicit one rather than an explicit one.

I'm inclined to take this PR as-is, and deal with testing Unicode in comments in `.msg` files separately, but I'm not sure.  @ros2/team thoughts?

**Comment by gavanderhoorn** [comment]
> On the other hand, we most definitely should support Unicode inside of comments in `.msg` files. This was a test of that, though more of an implicit one rather than an explicit one.

Didn't https://github.com/ros2/rcl_interfaces/pull/80 already add those?

---

Edit: oh, hm, you wrote "in comments". #80 does not test comments.

My vote would obviously be: implicit tests are no tests, and fix those missing tests in separate PR(s) ;)

**Review by sloretz — APPROVED** [review]
Changes LGTM!

My vote would be opening an issue on https://github.com/ros2/rosidl/issues about adding tests for non-ascii characters in comments in message files.

**Comment by clalancette** [comment]
> My vote would be opening an issue on https://github.com/ros2/rosidl/issues about adding tests for non-ascii characters in comments in message files.

That works for me.  @gavanderhoorn Would you mind opening up that issue?  Then we can run CI on this.

**Comment by gavanderhoorn** [comment]
See https://github.com/ros2/rosidl/issues/713.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17578/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12118/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18144/)

**Comment by gavanderhoorn** [comment]
Thanks for merging.

Would this be back-portable to Humble as well?

**Comment by clalancette** [comment]
Yeah, that seems reasonable.

@Mergifyio backport humble

**Comment by clalancette** [comment]
@Mergifyio backport humble

**Pull request merged**
