### PR TITLE
Added service_msgs dependency to solve a build error for a ROS 2 Jazzy workspace built from source

### PR DESCRIPTION
**Pull request by Mechazo11**
As part of a 3d robotics simulator, I put together a [ROS 2 Jazzy workspace](https://github.com/Mechazo11/ubuntu22_jazzy_ws) built from source files in Ubuntu 22.04.

When building all pertinent packages along with ```rcl_interfaces```, I ran into a dependency issue related to ```service_msgs```. This issue might have been reported last year in this answers.ros.org post: https://answers.ros.org/question/413630/issues-with-service_msgs/

I was able to solve this problem by simply adding the ```service_msgs``` dependency into `CmakeLists.txt` and `package.xml` files for the ```rcl_interfaces``` package and then tested to ensure it built correctly.

### CODE REVIEW

**Comment by clalancette** [comment]
I'm not entirely opposed to this, but do you know why this is necessary?  We don't seem to need it on Ubuntu 24.04, RHEL-9, or Windows.  And there are no direct dependencies in this package to `service_msgs`.  Could you share the actual error you are getting when trying to compile?

**Comment by Mechazo11** [comment]
Hi @clalancette sorry for the late response. I don't remember the exact error message. I will try to replicate the message again and send you a step-by-step instructions on how to replicating it in your end. Maybe I missed something cuz I agree, even I didn't understand why `service_msgs` was a dependency of `rcl_interface` even though without it, I couldn't get `rcl_interface` to build from source.

**Comment by Mechazo11** [comment]
Hi @clalancette I am not sure what was going on with my initial attempts, I just cloned the latest version of rcl_interface and it seems to build just fine without the need for the `service_msgs` dependency. I will go ahead and close this PR for now. In future, if the error comes back I will open a ticket to discuss it further.

**Comment by clalancette** [comment]
Thanks for looking into it!  And please do feel free to reopen if you see the problem again.

**Pull request closed without merging**
