### PR TITLE
Add message and service test fixtures

### PR DESCRIPTION
**Pull request by audrow**
Part of the fix for ros2/ros2cli#541.

### CODE REVIEW

**Comment by audrow** [comment]
This set of PRs seems to pass CI without breaking downstream packages.  I'll run the rest of CI once these PRs are reviewed.
[Build Status](http://ci.ros2.org/job/ci_linux/11854/)

**Comment by clalancette** [comment]
@audrow Friendly ping, what's the status of this?

**Comment by audrow** [comment]
It's waiting on consensus if we should add these additional test fixtures; the discussion is here: https://github.com/ros2/test_interface_files/pull/11. Once we have consensus, it just needs reviews (and perhaps to be rebased).

**Comment by audrow** [comment]
Closed in favor of https://github.com/ros2/ros2cli/pull/579.

**Pull request closed without merging**
