### PR TITLE
add array parameter types as defined in https://github.com/ros2/design/pull/152

### PR DESCRIPTION
**Pull request by mikaelarguedas**
This is to support @ayrton04's work on implementing parameter arrays

### CODE REVIEW

**Comment by ayrton04** [comment]
Do we also need to update `ParameterValue.msg`, or is it only meant do be defining primitive values?

https://github.com/ros2/rcl_interfaces/compare/master...ayrton04:param-arrays?expand=1

**Comment by mikaelarguedas** [comment]
> Do we also need to update `ParameterValue.msg`, or is it only meant do be defining primitive values?

Absolutely :+1: updated accordingly

**Review by ayrton04 — APPROVED** [review]
LGTM (or, at least, it matches what I have locally).

**Comment by mikaelarguedas** [comment]
@ayrton04 I split and merged the renaming of the existing parameter array. I'll leave this one open and we will merge it along the corresponding `rclcpp` PR you're working on

**Comment by ayrton04** [comment]
Awesome! I’m blocked at the moment because of this:

https://github.com/ros2/rcl_interfaces/issues/31

**Comment by mikaelarguedas** [comment]
Ack, that's indeed a problem that need to be solved.
Though we do recommend people making contributions to develop and test their features in a workspace tracking master and built from source as ardent code and API will be out of sync pretty quick.
If it helps there's you can setup an environment development using [this Dockerfile](https://github.com/osrf/docker_images/tree/master/ros2/source) (to track master you will need to replace `release-latest` with `master` [here](https://github.com/osrf/docker_images/blob/590a0ee1033a29b1a8aacda0030b0680a1e43e39/ros2/source/source/Dockerfile#L82))

**Comment by ayrton04** [comment]
Noted. Thanks for the heads-up, and for the fix!

**Comment by ayrton04** [comment]
Just a status update: I believe I'm all done with the rclcpp implementation, and am adding tests for `ParameterVariant`.

**Review by sloretz — APPROVED** [review]

**Pull request merged**
